name: Midnight
main: me.colingrimes.midnight.plugin.LoadingPlugin
version: ${version}
api-version: 1.21
author: Scill
load: STARTUP
softdepend: [PlaceholderAPI]
libraries:
  - com.zaxxer:HikariCP:6.3.0
  - org.postgresql:postgresql:42.7.5
  - com.mysql:mysql-connector-j:9.2.0
  - org.xerial:sqlite-jdbc:3.49.1.0