database:
  # Options: PostgreSQL, MySQL, SQLite
  storage-type: SQLite
  host: 'localhost'
  port: 3306
  database: 'minecraft'
  username: 'root'
  password: ''

messages:
  player-not-loaded: "&4&l❌ &cThis is awkward... Your chat data could not be loaded. Please relog."
